### ISSUE TITLE
Transfer Eraser to 'eraser-dev' GitHub organization

### ISSUE THREAD

**Issue by salaxander** [eraser-dev/eraser#790]
With acceptance into CNCF as a sandbox project, we need to move Eraser to a vendor neutral GitHub org. I will follow up with OSPO on this process, but I wanted to get the action item documented
```[tasklist]
### Tasks
- [x] update cla
- [x] transfer existing images in ghcr/Azure to ghcr/eraser-dev
- [x] add dco
- [x] check with OSPO about new org
- [x] update code of conduct
- [x] update security.md
- [x] move scanner template
- [x] update references in the scanner template @ashnamehrotra 
- [x] cut v1.2.0 from eraser-dev/eraser
```

**Comment by salaxander** [comment]
DCO has been added to the new org, so it'll be good to go once we transfer the repo

**Comment by justusbunsi** [comment]
Congratulations for being accepted as CNCF sandbox project. 🎉

Using your project for a while now and it helps a lot. Thank you 🙏.
With the relocation of the chart index.yaml I had some errors in my cluster because the old endpoint is not available anymore. Fixing that was a no-brainer, though. Have I missed a communication about the planned migration? I obviously missed this very issue for the last 3 weeks. 😅

**Comment by salaxander** [comment]
> Congratulations for being accepted as CNCF sandbox project. 🎉
> 
> Using your project for a while now and it helps a lot. Thank you 🙏. With the relocation of the chart index.yaml I had some errors in my cluster because the old endpoint is not available anymore. Fixing that was a no-brainer, though. Have I missed a communication about the planned migration? I obviously missed this very issue for the last 3 weeks. 😅

Hey @justusbunsi - sorry about the confusion here! The Helm change was a miss on our part. In the future we'll communicate any changes like this that might have user impact through the [mailing list](https://groups.google.com/g/eraser-dev) ahead of time
